# Generated by Django 4.2.3 on 2023-08-01 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Fathers_Name', models.CharField(max_length=70)),
                ('Email_Id', models.EmailField(max_length=100)),
                ('Contact_No', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
    ]
