# Generated by Django 4.2.4 on 2023-08-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_rename_user_usermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'permissions': [('can_view_email_id', 'Can View Email-ID')]},
        ),
    ]
